name: flutter_application_1
description: A new Flutter project

environment:
  sdk: '>=3.5.0 <4.0.0'  # Specify the Dart SDK version range

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2  # Use the latest version or the version that fits your needs
  url_launcher: ^6.0.9
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  video_player: ^2.9.2
  google_fonts: ^6.2.1
  share_plus: ^10.1.3
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Optional: linting rules

flutter:
  uses-material-design: true
  assets:
    - lib/assets/bitfcoin.png
    - lib/assets/virtual-currency.png
